# Generated by Django 4.2.7 on 2024-02-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('resim', models.FileField(blank=True, null=True, upload_to='ürünler/', verbose_name='Ürün Resmi')),
            ],
        ),
    ]
