# Generated by Django 4.2.7 on 2024-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=56, max_digits=10),
            preserve_default=False,
        ),
    ]
